image: cirrusci/flutter

pipelines:
  pull-requests:
    '**':
      - step:
          caches:
            - gradle
            - gradlewrapper
            - flutter
          deployment: test
          script:
            - echo "Show the configuration"
            - flutter doctor -v
            - echo "Running flutter analyze with linting rules"
            - flutter analyze
            - echo "Only on pull request"
            - echo "Building release APK..."
            - flutter -v build apk --flavor staging --dart-define=env="stag"
            #            - SLACK_TOKEN=xoxp-9185264976-714396107671-858766597156-207b1c4d8948f2b060763c11c8928504
            - SLACK_CHANEL=delivery_app_crash_report
            - SLACK_TOKEN=xoxe.xoxp-1-Mi0yLTM3MjI1NzYzODI5Mi0zMDU5ODQ5NTAxMzkyLTM0NjkxNDQ3OTgzNzItMzQ5MDU0NzgwNDgzMi0zYjg2ZTE5NDZlY2U5MDg1NDhjZjgwYzJlZjlmYzY1ODMxNTcwZjRlMGQ2YzkzMzYyOTYzNGNjZTY4Y2QxOTM4
            - BRANCH_SLUG="   ${BITBUCKET_BRANCH//\//-}"
            - FILE_NAME="$BITBUCKET_REPO_SLUG$BRANCH_SLUG.apk"
            - cp build/app/outputs/apk/release/app-release.apk "build/app/outputs/apk/release/$FILE_NAME"
            - curl -F file=@"build/app/outputs/apk/release/$FILE_NAME" -F channels=${SLACK_CHANEL} -F token=${SLACK_TOKEN} https://slack.com/api/files.upload
          artifacts:
            - build/app/outputs/apk/release/app-release.apk
definitions:
  caches:
    gradlewrapper: ~/.gradle/wrapper
    flutter: /opt/flutter