enum PreviousNetStatus { CONNECTED, DISCONNECTED, NONE }
enum ViewState {
  SHIMMER_STATE,
  NO_INTERNET_STATE,
  LIST_ERROR_STATE,
  LIST_EMPTY_STATE,
  LIST_VIEW_STATE
}
enum ListScrollEnum { UP, DOWN }
enum Gender { MALE, FEMALE }
